title: Notre-Dame de Paris
baseURL: https://lebeaurods.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: 'Home'
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: Custom bamboo rods and thought on spirituality
  facebook: ''
  favicon: ''
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  instagram: https://www.instagram.com/western_bamboo/
  youtube: ''
